### PR TITLE
Adding dynamic params

### PR DESCRIPTION
**Pull request by tdaron**
Hey there !

I were wondering, is it planned to support dynamic snippets using some params, something like this:

```c
for ($1 = 0; $1 < $2; $1++) {
}

```
and i could do something like
`
nap for int i users_length`

with 'for' as the snippet name.

Would this be something interesting to you ?

### CODE REVIEW

**Comment by tdaron** [comment]
Due to my implementation, this PR should not produce any breaking changes as if we don't provides params, then nothing is changed and it behaves like before.

The syntax of the params can be of course discussed !

**Comment by tdaron** [comment]
And, for the format, i'm not sure about $i format, idk which would be the best.

I just added $li which allows to lowercase a param. It can be usefull to do things like:

```c
typedef struct $1 {

} $l1_t;
```

which will map `nap struct Node` to 

```c
typedef struct Node {

} node_t;
```

**Comment by maaslalani** [comment]
Hey @Kaporos! Thanks so much for the PR for now I want to maintain the unix philosophy for nap to keep it simpler to maintain. That being said, you can use `sed` to perform exactly what you are trying to achieve here:

https://github.com/maaslalani/nap/issues/58#issuecomment-1865385058

**Comment by tdaron** [comment]
Got it for the unix part, and I didn't know about sed, I'll try to build my solution around it then !

**Comment by maaslalani** [comment]
Sounds good! In your main example you can do something like the following:

1. Store `for_loop` in `nap`:

```
for ($1 = 0; $1 < $2; $1++) {

}
```

2. Use `sed` to replace the variables:

```
nap for_loop | sed 's/$1/i/g;s/$2/users_length/g'
```

**Comment by tdaron** [comment]
Well, i did the script and it works nice (but bash is way less clean than go lmao)! 
Here is it if someone else interested in:

```bash
#!/bin/sh
if [ $# -eq 0 ]
then
echo "No args supplied"
exit 1
fi
C=$(nap $1)
# Loop through Bash script parameters
for ((i=1; i<=$#; i++)); do
    j=$((i-1))
    # Replace every $i with its value
    C=$(printf "$C" | sed "s/\$$j/${!i}/g")
    lowercase_i=$(echo "${!i}" | tr '[:upper:]' '[:lower:]')
    C=$(printf "$C" | sed "s/\$l$j/$lowercase_i/g")
done
printf "$C"
```

I also did it in nushell for lisibility

```nu
def main [...args] {
  if ($args | is-empty) {
    print "Not enough arguments"
    print "Usage: nu_nap <snippet> <arg1> <arg2>"
    exit 1
  }
  mut value = (nap $args.0)
  for arg in ($args | enumerate) {
    if ($arg.index == 0) {continue}
    $value = ($value | str replace -a $"$($arg.index)" $"($arg.item)")
    $value = ($value | str replace -a $"$l($arg.index)" $"($arg.item | str downcase)")
  }
  print $value
}
```

**Pull request closed without merging**
