### PR TITLE
feat: scan snippets

### PR DESCRIPTION
**Pull request by jolheiser**
ref #33 
closes #44

### CODE REVIEW

**Comment by cwarden** [comment]
Deleting a snippet doesn't touch the filesystem so restarting nap adds the file back.  Should "hard deletion" be a separate operation, e.g. bf9030a911de7e3838ea8c72d42c2e00fcd5d40b

**Comment by jolheiser** [comment]
Ah, I see, I was always doing testing via filesystem rather than the TUI. 🤦 

I know where to look now, thanks for the hint @cwarden

**Comment by jolheiser** [comment]
Yeah, I see this is a bit conflicting.

In my opinion, as we talked about briefly in #32, I like the idea that the filesystem is the source of truth rather than snippets.json

I am fine with either suggestion, do either of you have strong opinions for one over the other?

**Comment by cwarden** [comment]
I think delete should remove the file from the filesystem.  It's consistent with renaming shippets updating the filesystem.

**Comment by jolheiser** [comment]
Okay, I've implemented the feedback. 

https://github.com/maaslalani/nap/pull/45/commits/88edc927922d58c10df856d01670a377add7109e fixes the meta added to the JSON
https://github.com/maaslalani/nap/pull/45/commits/31340c5fccaceaf4cf9fdce39587ab2e2ee1367d removes the file from disk when removed in the TUI

**Comment by maaslalani** [comment]
It's looking good, just as a heads up I think it freezes on a fresh start. To reproduce I think you might need to try something like:

```
mkdir .nap-tmp
NAP_HOME=.nap-tmp nap
```

**Comment by jolheiser** [comment]
@maaslalani the problem was the default snippet not actually existing on disk, I've added a fix/cleanup in https://github.com/maaslalani/nap/pull/45/commits/9c5d84ea45c0dbb4fe892ad631aa367600a31625

**Comment by maaslalani** [comment]
Looking perfect, thank you so so much! @jolheiser

**Pull request merged**
